package com.bernaferrari.emojislider

import android.content.Context
import android.graphics.Color
import android.os.Build
import android.text.SpannableString
import com.bernaferrari.emojislider.drawables.TextDrawable
import com.facebook.rebound.Spring
import com.facebook.rebound.SpringConfig

internal fun Spring.origamiConfig(tension: Double, friction: Double): Spring =
    this.setSpringConfig(SpringConfig.fromOrigamiTensionAndFriction(tension, friction))

internal fun dpToPx(context: Context, x: Float): Int {
    return (x * context.resources.displayMetrics.density).toInt()
}

internal fun Context.getWidthPixels(): Int = this.resources.displayMetrics.widthPixels

internal fun textToDrawable(context: Context, text: String, size: Int): TextDrawable {
    return TextDrawable(
        context,
        context.getWidthPixels()
    ).apply {
        setSpannableValue(SpannableString(text))
        setTextSize(context.resources.getDimension(size))
    }
}

internal fun getCorrectColor(color0: Int, color1: Int, percentage: Float): Int {
    val red = Color.red(color0)
    val green = Color.green(color0)
    val blue = Color.blue(color0)
    return Color.rgb(
        red + ((Color.red(color1) - red).toFloat() * percentage).toInt(),
        green + ((Color.green(color1) - green).toFloat() * percentage).toInt(),
        blue + ((Color.blue(color1) - blue).toFloat() * percentage).toInt()
    )
}

/**
 * Returns a color associated with a particular resource ID
 *
 *
 * Starting in [android.os.Build.VERSION_CODES.M], the returned
 * color will be styled for the specified Context's theme.
 *
 * @param id The desired resource identifier, as generated by the aapt
 * tool. This integer encodes the package, type, and resource
 * entry. The value 0 is an invalid identifier.
 * @return A single color value in the form 0xAARRGGBB.
 * @throws android.content.res.Resources.NotFoundException if the given ID
 * does not exist.
 */
@Suppress("DEPRECATION")
internal fun Context.getColorCompat(id: Int): Int {
    return if (Build.VERSION.SDK_INT >= 23) {
        this.getColor(id)
    } else {
        this.resources.getColor(id)
    }
}